### ISSUE TITLE
Implementacao que fere o principio ISP

### ISSUE THREAD

**Issue by plannersistemas** [RenatoAv/desafio-solid#2]
oi @RenatoAv vc pode implementar um código que fere o princípio ISP.
 como vc citou no readme.md

*"Problema: A interface IMatricular declara três metodos criarMatricula,RegistrarCurso,RegistrarBolsa.Uma classe AlunoComum seria obrigado a implementar método RegistrarBolsa"*

Obs: vc pode criar uma NOVA pasta chamada `bad` onde será implementado essa rotina, não esquece da classe App.java executando

**Comment by RenatoAv** [comment]
Exemplo criado!
